apiVersion: v1
kind: Service
metadata:
  name: boston-housing-service
spec:
  selector:
    app: boston-housing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080 # 手動指定或讓系統自動分配
  type: NodePort
